version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env.production

  frontend:
    build:
      context: ./client
    ports:
      - "8080:80"
    depends_on:
      - backend